GET http://localhost:5000/rft/countdef

###

POST http://localhost:5000/passes HTTP/1.1
Content-Type: application/json

{
    "line": "Line 1",
    "status": "Passed",
    "code": "OK",
    "qty": 1
}

###
POST http://localhost:5000/rft/issues HTTP/1.1
Content-Type: application/json

{
    "code"  : "31",
    "label" : "OTHER"
}

###
GET http://localhost:5000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJhZG1pbiIsImxpbmUiOiJ0ZXN0Iiwicm9sZSI6InJvb3QiLCJpYXQiOjE2NTY5OTAzNTYsImV4cCI6MTY1Njk5MDM3Nn0.PGQKYRklqKdQURsuyXQX5HUQAJTm-iV3z8xBs56LaVw

###
POST http://localhost:5000/users HTTP/1.1
Content-Type: application/json

{
    "name": "admin3",
    "line": "Line3",
    "role": "root",
    "password": "12345",
    "confPassword": "12345"
}

###
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
    "name": "admin",
    "password": "12345"
}

###
GET http://localhost:5000/charts/view1 HTTP/1.1
